In [2]:
import numpy as np 
import pandas as pd

In [3]:
books = pd.read_csv('books.csv')

C:\Users\cccc\AppData\Local\Temp\ipykernel_21464\1848672579.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('books.csv')

In [4]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [5]:
books = books[['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher']]

In [6]:
books.head(3)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial

In [7]:
books.rename(columns={'Book-Title':'title', 'Book-Author':'author', 'Year-Of-Publication':'year', 'Publisher':'publisher'},inplace=True)

In [8]:
books.head(3)

,ISBN,title,author,year,publisher
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial

In [9]:
users = pd.read_csv('Users.csv')

In [10]:
users.head(3)

   User-ID                         Location   Age
0        1               nyc, new york, usa   NaN
1        2        stockton, california, usa  18.0
2        3  moscow, yukon territory, russia   NaN

In [11]:
users.rename(columns={'User-ID':'user_id', 'Location':'location', 'Age':'age'},inplace=True)

In [12]:
users.head(3)

   user_id                         location   age
0        1               nyc, new york, usa   NaN
1        2        stockton, california, usa  18.0
2        3  moscow, yukon territory, russia   NaN

In [13]:
ratings = pd.read_csv('Ratings.csv')

In [14]:
ratings.head(3)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0

In [15]:
ratings.rename(columns={'User-ID':'user_id', 'Book-Rating':'rating'},inplace=True)

In [16]:
ratings.head(3)

   user_id        ISBN  rating
0   276725  034545104X       0
1   276726  0155061224       5
2   276727  0446520802       0

In [17]:
books.shape

(271360, 5)

In [18]:
users.shape

(278858, 3)

In [19]:
ratings.shape

(1149780, 3)

In [20]:
x = ratings['user_id'].value_counts() > 200

In [21]:
y = x[x].index

In [22]:
ratings = ratings[ratings['user_id'].isin(y)]

In [23]:
ratings.shape

(526356, 3)

In [24]:
ratings_with_books = ratings.merge(books, on='ISBN')

In [25]:
ratings_with_books.head(3)

,user_id,ISBN,rating,title,author,year,publisher
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning

In [26]:
ratings_with_books.shape

(487671, 7)

In [27]:
number_rating = ratings_with_books.groupby('title')['rating'].count().reset_index()

In [28]:
number_rating.rename(columns={'rating':'number of rating'},inplace=True)

In [29]:
number_rating.head(3)

                                               title  number of rating
0   A Light in the Storm: The Civil War Diary of ...                 2
1                              Always Have Popsicles                 1
2               Apple Magic (The Collector's series)                 1

In [30]:
final_rating = ratings_with_books.merge(number_rating, on='title')

In [31]:
final_rating.head(3)

,user_id,ISBN,rating,title,author,year,publisher,number of rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,7
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,1

In [32]:
final_rating.shape

(487671, 8)

In [33]:
final_rating = final_rating[final_rating['number of rating'] >= 50]

In [34]:
final_rating.shape

(61853, 8)

In [35]:
final_rating.drop_duplicates(['user_id','title'], inplace=True)

In [36]:
final_rating.shape

(59850, 8)

In [37]:
book_pivot = final_rating.pivot_table(columns='user_id', index='title', values='rating')

In [38]:
book_pivot.head(3)

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN

In [39]:
book_pivot.shape

(742, 888)

In [40]:
book_pivot.fillna(0, inplace=True)

In [41]:
book_pivot.head(3)

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [42]:
from scipy.sparse import csr_matrix

book_sparse = csr_matrix(book_pivot)

In [43]:
type(book_sparse)

scipy.sparse._csr.csr_matrix

In [44]:
from sklearn.neighbors import NearestNeighbors

model = NearestNeighbors(algorithm='brute')

In [45]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [46]:
distances, suggestions = model.kneighbors(book_pivot.iloc[237, :].values.reshape(1,-1), n_neighbors=6)

In [47]:
suggestions

array([[237, 238, 240, 241, 184, 536]])

In [48]:
for i in range(len(suggestions)):
    print(book_pivot.index[suggestions[i]])

Index(['Harry Potter and the Chamber of Secrets (Book 2)',
       'Harry Potter and the Goblet of Fire (Book 4)',
       'Harry Potter and the Prisoner of Azkaban (Book 3)',
       'Harry Potter and the Sorcerer's Stone (Book 1)', 'Exclusive',
       'The Cradle Will Fall'],
      dtype='object', name='title')

In [49]:
int(np.where(book_pivot.index == 'Animal Farm')[0][0])

54

In [50]:
def recommend_book(book_name):
    book_id = int(np.where(book_pivot.index == book_name)[0][0])
    distances, suggestions = model.kneighbors(book_pivot.iloc[book_id, :].values.reshape(1,-1), n_neighbors=6)

    for i in range(len(suggestions[0])):
        if i == 0:
            continue
        else:
            print(book_pivot.index[suggestions[0][i]])

In [51]:
recommend_book('Harry Potter and the Chamber of Secrets (Book 2)')

Harry Potter and the Goblet of Fire (Book 4)
Harry Potter and the Prisoner of Azkaban (Book 3)
Harry Potter and the Sorcerer's Stone (Book 1)
Exclusive
The Cradle Will Fall

In [52]:
import joblib 

joblib.dump(model, 'book_recommender.pkl')

['book_recommender.pkl']

In [115]:
book_pivot.to_csv('book_set.csv')